version: '1'

services:
  web:
    tty: true
    stdin_open: true
    environment:
      - PORT=8000
    build:
      context: .
    volumes:
      - .:/opt/neon-www
    ports:
      - '8000:8000'
    command: /bin/sh -c "yarn install --pure-lockfile && npm start"

volumes:
  mongo:
